version: "3.5"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - web_net

  web:
    image: registry.thiswjk.xyz/will/web:latest
    volumes:
      - ./:/mysite
      - /tmp/logs:/tmp
    networks:
      - nginx-net
      - web_net
      - redis_net
    environment:
      VIRTUAL_HOST: api.thiswjk.xyz
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.thiswjk.xyz
      LETSENCRYPT_EMAIL: kangmang92@gmail.com

  redis-master:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - redis_net

  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    deploy:
      replicas: 2
    networks:
      - redis_net

  sentinel:
    image: registry.thiswjk.xyz/will/sentinel:latest
    ports:
      - 26379:26379
    deploy:
      replicas: 3
    networks:
      - redis_net
    environment:
      - REDIS_MASTER_HOST=redis-master
      
networks:
  web_net:
    name: web_net
  redis_net:
    name: redis_net
  nginx-net:
    external: true