version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - web_net

  web:
    image: registry.thiswjk.xyz/web:latest
    volumes:
      - ./:/mysite
      - /tmp/logs:/tmp
    command: bash start.sh  # 执行命令，有多种格式
    depends_on:
      - db
      - sentinel
      - redis-master
    networks:
      - nginx-net
      - web_net

  redis-master:
    image: redis:latest
    ports:
     - 6379:6379
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - web_network
      - redis_net

  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    deploy:
      replicas: 2
    networks:
      - redis_net

  sentinel:
    image: registry.thiswjk.xyz/sentinel:latest
    deploy:
      replicas: 3
    networks:
      - redis_net
      
networks:
  redis_net:
  nginx-net:
    external: true