# Generated by Django 2.2.3 on 2019-08-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
    ]
